apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    type: voting-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    tier: frontend-voting-app
  