apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
spec:
  template:
    metadata:
     name: voting-app-pod
     labels:
       tier: frontend-voting-app
    spec:
      containers:
        - name: voting-app-container
          image: kodekloud/examplevotingapp_vote:v1


  replicas: 3
  selector:
    matchLabels:
      tier: frontend-voting-app
