apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  template:
    metadata:
      name: db
      labels:
        type: postgresql-database
    spec:
      containers:
        - name: postgresql-database
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
  replicas: 1
  selector:
    matchLabels:
      type: postgresql-database
