apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    type: front-end-result-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    type: frontend-result-app
